FROM your_base_image_here:latest
USER user
# ENV DEBIAN_FRONTEND noninteractive
# ENV DEBCONF_NONINTERACTIVE_SEEN true
WORKDIR your_working_directory_here
LABEL maintainer="SunshineCloudSoft"
ENTRYPOINT ["/usr/bin/bash", "-c"]
CMD ["your_cmd_here"]